#!/usr/bin/env python3
"""Regenerate the open-chunk index inside docs/status/START_HERE.md.

    python3 scripts/maintenance/plan_index.py            # rewrite the block
    python3 scripts/maintenance/plan_index.py --check    # exit 1 if it is stale

START_HERE.md is what a cold-start agent reads instead of paging through
PROJECT_PLAN.md (660 KB). Its prose is hand-written and stable; the one part
that moves daily — which chunks are open — is generated here from the §7 table
rows between the BEGIN/END markers, so there is no second, hand-edited status
list to drift. PROJECT_PLAN.md §7 stays the single authority: this only reads
it. One line per open chunk: ID, status glyph, tier, title cut to 90 chars,
and the plan line number to jump to.

Read-only on the plan, stdlib only, no solves.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PLAN = ROOT / "PROJECT_PLAN.md"
TARGET = ROOT / "docs" / "status" / "START_HERE.md"
BEGIN = "<!-- BEGIN generated by scripts/maintenance/plan_index.py — do not edit by hand -->"
END = "<!-- END generated -->"
# §3 status legend. Order matters only for "first glyph in the status cell".
GLYPHS = ("✅", "🟡", "⬜", "🧪", "🚫", "⚠️", "❌", "⏸️", "🔁", "⬛")
DONE = {"✅", "🚫", "⬛"}   # ⬛ = WON'T FIX (`OPS-16`)
ROW = re.compile(r"^\| `([A-Z]+-\d+[a-z]?)` \|")


def split_cells(row: str) -> list[str]:
    return [c.strip() for c in re.split(r"(?<!\\)\|", row)[1:-1]]


def clean(title: str, width: int = 90) -> str:
    title = re.sub(r"\*\*|~~", "", title)
    title = re.split(r" — | \*\(|\. ", title, maxsplit=1)[0].strip()
    return title if len(title) <= width else title[: width - 1].rstrip() + "…"


def build() -> list[str]:
    families: dict[str, list[str]] = {}
    closed = total = 0
    in7 = False
    for n, line in enumerate(PLAN.read_text(encoding="utf-8").split("\n"), 1):
        if line.startswith("## "):
            in7 = line.startswith("## 7.")
        m = ROW.match(line) if in7 else None
        if not m:
            continue
        cells = split_cells(line)
        if len(cells) < 4:
            continue
        total += 1
        # Titles carry unescaped pipes (`σ|E|²`, `|B|`), so cell positions are
        # not reliable. The status cell is the first one, after the title's
        # first cell, that LEADS with a legend glyph; the tier follows it.
        idx = next((i for i in range(2, len(cells))
                    if cells[i].lstrip("*_ ").startswith(GLYPHS)), None)
        if idx is None:
            glyph, title, tier = "?", cells[1], ""
        else:
            glyph = next(g for g in GLYPHS if cells[idx].lstrip("*_ ").startswith(g))
            title = "|".join(cells[1:idx])
            tier = cells[idx + 1] if idx + 1 < len(cells) else ""
        if glyph in DONE:
            closed += 1
            continue
        fam = re.match(r"[A-Z]+", m.group(1)).group(0)
        tier_word = re.match(r"(smoke|standard|heavy|xl|xxl|unmeasured)", tier)
        families.setdefault(fam, []).append(
            f"- `{m.group(1)}` {glyph} {tier_word.group(0) if tier_word else '—'} — {clean(title)} *(plan:{n})*")
    out = [BEGIN, "",
           f"**{total - closed} open of {total} chunks** (✅ / 🚫 / ⬛ omitted). Glyphs: PROJECT_PLAN.md §3. "
           "`plan:N` is the §7 row's line — read that row, not the section.", ""]
    for fam in sorted(families):
        out += [f"**{fam}**", ""] + families[fam] + [""]
    out.append(END)
    return out


def main() -> int:
    text = TARGET.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"markers missing in {TARGET}", file=sys.stderr)
        return 2
    head, rest = text.split(BEGIN, 1)
    tail = rest.split(END, 1)[1]
    new = head + "\n".join(build()) + tail
    if "--check" in sys.argv[1:]:
        if new != text:
            print("STALE: docs/status/START_HERE.md open-chunk index does not match PROJECT_PLAN.md §7 — "
                  "run scripts/maintenance/plan_index.py")
            return 1
        print("current: START_HERE.md open-chunk index matches PROJECT_PLAN.md §7")
        return 0
    TARGET.write_text(new, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(new)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
