"""`GEO-14` step 1: is the ~3% Larmor-sphere residual a floor or resolution?

Three residuals sit at ~3% on *curved* fixtures — `TH-10`'s 64 MHz interior
field (3.643%), its ohmic-power integral (3.629%), and `MAG-13`'s CG1 wire
floor (3.7372% at 1.52 M cells).  The commissioning hypothesis (PROJECT_PLAN
§7 `GEO-14`) is that all three are one shared **faceting** floor: a
piecewise-flat tetrahedral surface approximating a curved boundary, whose
error does not fall the way a volume-resolution error does.

The discriminator is one command, and it is cheap because the mesh is already
priced: `TH-10` step 3 solved the **128 MHz** gate at ``h_sphere = 0.00556``
(55 251 cells, 1.826%, separation 57.31×).  Step 1 here re-runs the **64 MHz**
gate — nothing else changed — at that same mesh.

**Pre-registered bands** (stated in §7 before this file existed; classification
is printed, not asserted, because all three are legitimate readings):

* relL2 stays **> 3.0%** ⇒ the 3.643% is a floor, not resolution — faceting is
  confirmed as its owner at 64 MHz, and `GEO-14` step 2 (surface-graded sizing)
  is worth scoping.
* relL2 falls **< 2.0%** ⇒ it was resolution all along and `TH-10` step 3's
  inference — "the error is lower at 128 MHz at the same mesh, so the ~3% is
  not wavelength-limited" — needs rewriting.
* between ⇒ mixed; report both.

**Negative control, asserted:** the same command reproduces `TH-10` step 3's
recorded 128 MHz digits at that mesh (1.826% relL2, 57.31× separation) to a
pre-stated 1% relative band — the band `EX-19` measured this fixture's
reproducibility at (max drift 1.7e-04, 2026-08-13).  A run that moves the
*recorded* frequency's numbers is a bug in this file or in the fixture, not a
finding about geometry; without that control a "3% floor" reading could just
be a differently-meshed sphere.  The cell count is asserted against the priced
55 251 for the same reason: "the same mesh" is the whole experiment.

Scope: **measurement only.**  `TH-10` is ✅ and does not reopen under any band
— its gates are levels ("< 5%, decreasing"), not floor attributions, and this
file asserts `TH-10`'s own 5% band at the finer mesh rather than a new one.
The fixture is imported from `test_lossy_sphere_fullwave`, never restated:
a second copy of the sphere recipe would make any difference between the two
files uninterpretable.

**Result (2026-08-13, `20260813T213156Z_GEO-14-step1-discriminator.log`):** the
**RESOLUTION** band — 3.643% → **1.781%** at 3.13× the cells, improvement
2.046× for a 1.5× step in h (observed rate 1.77 in h, i.e. still converging,
not floored).  Control exact: 55 251 cells, 128 MHz at 1.826% / 57.31×, drift
1.8e-05 / 7.2e-05.  Two readings follow and only the first is the band's:

1. the shared-faceting-floor hypothesis is **refuted at 64 MHz** — the residual
   is mesh resolution and falls faster than O(h); `GEO-14` step 2
   (surface-graded sizing) loses its premise on this fixture;
2. the band's trailing clause — pre-registered as "the step-3 inference is
   wrong" — over-reached, and the measurement says the opposite: at this mesh
   64 MHz (1.781%) and 128 MHz (1.826%) sit together, as they did at the
   coarser mesh (3.643% / 3.299%), so `TH-10` step 3's actual inference (the
   residual is **not** wavelength-limited) is *strengthened*, not overturned.
   The two claims were conflated when the band was written; the band name is
   left exactly as registered rather than re-worded after the fact.

Run (complex build required)::

    docker compose exec -T fem-em-solver bash -lc \\
      'source /usr/local/bin/dolfinx-complex-mode && cd /workspace && \\
       PYTHONPATH=/workspace/src FEM_EM_REQUIRE_COMPLEX=1 \\
       mpiexec -n 2 python3 -m pytest tests/environment \\
       tests/validation/test_geometry_floor_discriminator.py -v -s'
"""

from __future__ import annotations

import pytest
from mpi4py import MPI

from tests.complex_mode import complex_only
from tests.validation.test_lossy_sphere_fullwave import (
    FREQUENCY_64_HZ,
    FREQUENCY_128_HZ,
    INTERIOR_L2_BOUND,
    RESOLUTIONS_128,
    _series,
    _solve,
)

# `TH-10` step 3's fine rung, verbatim: the already-priced mesh (26 s on
# record for the whole 128 MHz gate, `20260813T123211Z_TH-10-step3-128mhz.log`).
DISCRIMINATOR_RESOLUTION = RESOLUTIONS_128[-1]
PRICED_CELL_COUNT = 55251

# `TH-10` step 3's recorded 128 MHz numbers at exactly this mesh.
RECORD_128_RELL2 = 0.01826
RECORD_128_SEPARATION = 57.31
# Reproduction band, pre-stated: `EX-19` reproduced four records through a
# second code path at max drift 1.7e-04, so 1% is ~60× the observed drift and
# still far tighter than any of the bands being discriminated between.
REPRODUCTION_BAND = 0.01
# The mesh is generated by gmsh from the same two sizes; the count is expected
# to be exact, and 1% allows for nothing more than a gmsh version bump.
CELL_COUNT_BAND = 0.01

# The §7 pre-registered bands.
FLOOR_BAND = 0.030
RESOLUTION_BAND = 0.020

# `TH-10` step 2's record at its own fine rung (17 670 cells), for the printed
# comparison only.
RECORD_64_RELL2_COARSER_MESH = 0.03643


def _classify(err: float) -> str:
    if err > FLOOR_BAND:
        return (
            "FLOOR — faceting confirmed as owner at 64 MHz; GEO-14 step 2 "
            "(surface-graded sizing) is worth scoping"
        )
    if err < RESOLUTION_BAND:
        return (
            "RESOLUTION — the 3.643% was resolution; TH-10 step 3's "
            "not-wavelength-limited inference needs rewriting"
        )
    return "MIXED — report both; neither pre-registered band is reached"


@complex_only
@pytest.mark.integration
def test_larmor_sphere_residual_at_the_priced_fine_mesh():
    """64 MHz at 128 MHz's mesh, with the 128 MHz record as the control."""
    comm = MPI.COMM_WORLD
    h_sphere, h_far = DISCRIMINATOR_RESOLUTION

    err_64, qs_64, ncells_64 = _solve(_series(FREQUENCY_64_HZ), h_sphere, h_far)
    err_128, qs_128, ncells_128 = _solve(_series(FREQUENCY_128_HZ), h_sphere, h_far)
    sep_64 = qs_64 / err_64
    sep_128 = qs_128 / err_128

    cell_drift = abs(ncells_64 - PRICED_CELL_COUNT) / PRICED_CELL_COUNT
    rell2_drift = abs(err_128 - RECORD_128_RELL2) / RECORD_128_RELL2
    sep_drift = abs(sep_128 - RECORD_128_SEPARATION) / RECORD_128_SEPARATION
    improvement = RECORD_64_RELL2_COARSER_MESH / err_64

    if comm.rank == 0:
        print(
            f"\n[GEO-14 1] the ~3% floor discriminator: TH-10's 64 MHz gate at "
            f"TH-10 step 3's already-priced fine mesh, h_sphere = {h_sphere:.5f}"
        )
        print(
            f"  mesh: {ncells_64} cells (priced {PRICED_CELL_COUNT}, "
            f"drift {cell_drift:.2e}); 128 MHz solve on the same mesh: "
            f"{ncells_128} cells"
        )
        print(
            f"  NEGATIVE CONTROL, 128 MHz: relL2 = {err_128:.3%} vs recorded "
            f"{RECORD_128_RELL2:.3%} (drift {rell2_drift:.2e}); separation = "
            f"{sep_128:.2f}x vs recorded {RECORD_128_SEPARATION:.2f}x "
            f"(drift {sep_drift:.2e}); band {REPRODUCTION_BAND:.0%}"
        )
        print(
            f"  MEASUREMENT, 64 MHz: relL2 = {err_64:.3%} at {ncells_64} cells, "
            f"against {RECORD_64_RELL2_COARSER_MESH:.3%} at 17 670 cells "
            f"(3.13x the cells, h down 1.5x) => improvement factor "
            f"{improvement:.3f}x; separation = {sep_64:.2f}x"
        )
        print(
            f"  pre-registered bands: > {FLOOR_BAND:.1%} floor / "
            f"< {RESOLUTION_BAND:.1%} resolution / between mixed"
        )
        print(f"  READING: {_classify(err_64)}")

    assert cell_drift < CELL_COUNT_BAND, (
        f"the discriminator ran on {ncells_64} cells, not the priced "
        f"{PRICED_CELL_COUNT} — 'the same mesh' is the entire experiment, so a "
        f"moved cell count invalidates the comparison against TH-10 step 3's "
        f"record before any band is read"
    )
    assert ncells_128 == ncells_64, (
        f"the two frequencies meshed differently ({ncells_64} vs {ncells_128} "
        "cells) — the control and the measurement must share one mesh"
    )
    assert rell2_drift < REPRODUCTION_BAND, (
        f"the 128 MHz relL2 moved to {err_128:.4%} from the recorded "
        f"{RECORD_128_RELL2:.4%} ({rell2_drift:.2%} > "
        f"{REPRODUCTION_BAND:.0%}) at the mesh it was recorded on. That is a "
        "regression in the fixture or this file, not a geometry finding — the "
        "64 MHz reading above must not be interpreted until it is explained"
    )
    assert sep_drift < REPRODUCTION_BAND, (
        f"the 128 MHz quasi-static separation moved to {sep_128:.3f}x from the "
        f"recorded {RECORD_128_SEPARATION:.2f}x ({sep_drift:.2%} > "
        f"{REPRODUCTION_BAND:.0%}); same reading as above"
    )
    assert err_64 < INTERIOR_L2_BOUND, (
        f"64 MHz interior relL2 is {err_64:.3%} at {ncells_64} cells, outside "
        f"TH-10's own {INTERIOR_L2_BOUND:.0%} band — which it passed at 3.13x "
        "fewer cells. Refining a passing gate into a failing one is a defect, "
        "not a floor measurement"
    )
